Node buildHuffmanTree(QueueNode);
int storeHuffmanCodes(Node, char[127][8], char[8], int);
int setHeader(int*, char*);
int encodeStringToHuffman(char*, char*, char[127][8], int*);
char* intToCharArray(int);
int convertCharToBitArray(char*, int*);
int binaryToDecimal(int*);
int decimalToBinary(int, int*);
int decodeFromHuffman(char*);
Node readHeader(char*);
